// Generated by github.com/davyxu/tabtoy
// Version: 2.9.0
// DO NOT EDIT!!
using System.Collections.Generic;

namespace DC
{
	
	

	// Defined in table: ParamsCfgMgr
	
	public partial class ParamsCfgMgr
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// ParamsConfig
		/// </summary>
		public List<ParamsConfigDefine> ParamsConfig = new List<ParamsConfigDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, ParamsConfigDefine> _ParamsConfigByID = new Dictionary<int, ParamsConfigDefine>();
        public ParamsConfigDefine GetParamsConfigByID(int ID, ParamsConfigDefine def = default(ParamsConfigDefine))
        {
            ParamsConfigDefine ret;
            if ( _ParamsConfigByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(ParamsConfigDefine) )
			{
				TableLogger.ErrorLine("GetParamsConfigByID failed, ID: {0}", ID);
			}

            return def;
        }
		
		public string GetBuildID(){
			return "d41d8cd98f00b204e9800998ecf8427e";
		}
	
		#endregion
		#region Deserialize code
		
		static tabtoy.DeserializeHandler<ParamsCfgMgr> _ParamsCfgMgrDeserializeHandler;
		static tabtoy.DeserializeHandler<ParamsCfgMgr> ParamsCfgMgrDeserializeHandler
		{
			get
			{
				if (_ParamsCfgMgrDeserializeHandler == null )
				{
					_ParamsCfgMgrDeserializeHandler = new tabtoy.DeserializeHandler<ParamsCfgMgr>(Deserialize);
				}

				return _ParamsCfgMgrDeserializeHandler;
			}
		}
		public static void Deserialize( ParamsCfgMgr ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.ParamsConfig.Add( reader.ReadStruct<ParamsConfigDefine>(ParamsConfigDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build ParamsConfig Index
			for( int i = 0;i< ins.ParamsConfig.Count;i++)
			{
				var element = ins.ParamsConfig[i];
				
				ins._ParamsConfigByID.Add(element.ID, element);
				
			}
			
		}
		static tabtoy.DeserializeHandler<ParamsConfigDefine> _ParamsConfigDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<ParamsConfigDefine> ParamsConfigDefineDeserializeHandler
		{
			get
			{
				if (_ParamsConfigDefineDeserializeHandler == null )
				{
					_ParamsConfigDefineDeserializeHandler = new tabtoy.DeserializeHandler<ParamsConfigDefine>(Deserialize);
				}

				return _ParamsConfigDefineDeserializeHandler;
			}
		}
		public static void Deserialize( ParamsConfigDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.ID = reader.ReadInt32();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Name = reader.ReadString();
                	}
                	break; 
                	case 0x60002:
                	{
						ins.Value = reader.ReadString();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
	

	} 

	// Defined in table: ParamsConfig
	[System.Serializable]
	public partial class ParamsConfigDefine
	{
	
		
		/// <summary> 
		/// ID
		/// </summary>
		public int ID = 0; 
		
		/// <summary> 
		/// 名称
		/// </summary>
		public string Name = ""; 
		
		/// <summary> 
		/// 值
		/// </summary>
		public string Value = ""; 
	
	

	} 

}
