# Generated by Django 3.0.3 on 2020-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_guser'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='u_token',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
