// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonActor.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dcgameprotobuf {

  /// <summary>Holder for reflection information generated from CommonActor.proto</summary>
  public static partial class CommonActorReflection {

    #region Descriptor
    /// <summary>File descriptor for CommonActor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonActorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDb21tb25BY3Rvci5wcm90bxIOZGNnYW1lcHJvdG9idWYiLgoKUEFjdG9y",
            "RGF0YRIPCgdhY3RvckhwGAEgASgFEg8KB2FjdG9yTXAYAiABKAViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dcgameprotobuf.PActorData), global::Dcgameprotobuf.PActorData.Parser, new[]{ "ActorHp", "ActorMp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PActorData : pb::IMessage<PActorData> {
    private static readonly pb::MessageParser<PActorData> _parser = new pb::MessageParser<PActorData>(() => new PActorData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PActorData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dcgameprotobuf.CommonActorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PActorData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PActorData(PActorData other) : this() {
      actorHp_ = other.actorHp_;
      actorMp_ = other.actorMp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PActorData Clone() {
      return new PActorData(this);
    }

    /// <summary>Field number for the "actorHp" field.</summary>
    public const int ActorHpFieldNumber = 1;
    private int actorHp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActorHp {
      get { return actorHp_; }
      set {
        actorHp_ = value;
      }
    }

    /// <summary>Field number for the "actorMp" field.</summary>
    public const int ActorMpFieldNumber = 2;
    private int actorMp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActorMp {
      get { return actorMp_; }
      set {
        actorMp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PActorData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PActorData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActorHp != other.ActorHp) return false;
      if (ActorMp != other.ActorMp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActorHp != 0) hash ^= ActorHp.GetHashCode();
      if (ActorMp != 0) hash ^= ActorMp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActorHp != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ActorHp);
      }
      if (ActorMp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActorMp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActorHp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActorHp);
      }
      if (ActorMp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActorMp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PActorData other) {
      if (other == null) {
        return;
      }
      if (other.ActorHp != 0) {
        ActorHp = other.ActorHp;
      }
      if (other.ActorMp != 0) {
        ActorMp = other.ActorMp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActorHp = input.ReadInt32();
            break;
          }
          case 16: {
            ActorMp = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
