// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ParamsConfig.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dcgameprotobuf {

  /// <summary>Holder for reflection information generated from ParamsConfig.proto</summary>
  public static partial class ParamsConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for ParamsConfig.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ParamsConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQYXJhbXNDb25maWcucHJvdG8SDmRjZ2FtZXByb3RvYnVmKjUKDVBQYXJh",
            "bXNDb25maWcSEAoMZW1wdHlfaG9sZGVyEAASEgoOYmVnaW5uZXJfc2NlbmUQ",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dcgameprotobuf.PParamsConfig), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PParamsConfig {
    [pbr::OriginalName("empty_holder")] EmptyHolder = 0,
    [pbr::OriginalName("beginner_scene")] BeginnerScene = 1,
  }

  #endregion

}

#endregion Designer generated code
